"""Deterministic ARCHITECTURE.md.

This renderer never calls a model. ``foothold docs --narrate`` adds prose on
top of exactly this structure, so the document remains useful, and correct,
without an API key.
"""

from __future__ import annotations

from foothold.models import RepoMap
from foothold.render.mermaid import render_mermaid


def render_architecture(repo: RepoMap, top: int = 20, narrative: str | None = None) -> str:
    sources = [m for m in repo.modules.values() if not m.is_test]
    parts = [
        "# Architecture",
        "",
        "<!-- Generated by foothold. Re-run `foothold docs` to refresh. -->",
        "",
        f"{len(repo.modules)} modules ({len(sources)} source), {repo.loc_total:,} lines, "
        f"{len(repo.edges)} import statements.",
        "",
    ]
    if narrative:
        parts += ["## Overview", "", narrative, ""]
    parts += ["## Where to start", ""]
    for name in repo.entrypoints[:6]:
        module = repo.modules[name]
        summary = (module.docstring or "").strip().splitlines()
        parts.append(f"- `{module.path}` — {summary[0] if summary else 'no docstring'}")
    parts += [
        "",
        "## Core modules",
        "",
        "| File | Score | Imported by | Lines | Signals |",
        "|---|---:|---:|---:|---|",
    ]
    for score in repo.scores[:top]:
        parts.append(
            f"| `{score.path}` | {score.total:.3f} | {score.fan_in} | {score.loc} | "
            f"{', '.join(score.reasons) or '—'} |"
        )
    parts += ["", "## Dependency graph", "", render_mermaid(repo), ""]
    if repo.cycles:
        parts += ["## Import cycles", ""]
        parts += [f"- {' → '.join(c)}" for c in repo.cycles[:5]]
        parts.append("")
    parts += [
        "## How this file is scored",
        "",
        "`score = 0.45·pagerank + 0.30·churn + 0.15·fan-in + 0.10·log(loc)`, each term "
        "min-max normalised across the repository. Weights are configurable in "
        "`.foothold.toml`.",
        "",
    ]
    return "\n".join(parts)
